.class public final Lcom/android/ntduc/chatgpt/App_ComponentTreeDeps;
.super Ljava/lang/Object;


# annotations
.annotation build Ldagger/hilt/internal/componenttreedeps/ComponentTreeDeps;
    aggregatedDeps = {
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_App_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_di_AppModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_di_DataModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_di_DatabaseModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_di_ErrorModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_di_NetworkModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_service_OverlayService_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_crop_image_CropImageActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_detailart_ImageDetailActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_detailart_fragment_ResultImageDetailFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_grammar_GrammarActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_grammar_fragments_GrammarCheckFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_grammar_fragments_GrammarCheckResultFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_iap_fragment_WelcomePurchasedFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_iap_iap1_IAP1Activity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_iap_iap1_IAP1LifeTimeActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_iap_iap2_IAP2Activity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_iap_iap2_IAP2LifeTimeActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_iap_iap2_IAP2WeeklyActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_iap_iap3_IAP3Activity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_iap_welcome_WelcomePurchasedActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_language_LanguageActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_MainActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_art_ArtFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_art_chat_ResultImageFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_character_CharacterFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_character_detail_DetailCharacterFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_chat_ChatFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_pdf_PdfFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_pdf_chat_ChatPdfFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_setting_SettingFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_setting_support_LiveSupportFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_setting_theme_ChillThemeFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_setting_theme_ThemeFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_setting_widget_WidgetFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_setting_widget_instruction_InstructionWidgetActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_setting_widget_instruction_fragment_ItemInstructionWidgetFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_topic_TopicFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_topic_history_HistoryChatFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_main_fragment_topic_question_QuestionFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_fullscreen_OnboardFullscreenActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_fullscreen_first_FirstOnboardFullscreenFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_fullscreen_second_SecondOnboardFullscreenFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_fullscreen_third_ThirdOnboardFullscreenFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal2_OnboardNormal2Activity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal2_first_FirstOnboardNormal2Fragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal2_second_SecondOnboardNormal2Fragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal2_third_ThirdOnboardNormal2Fragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal3_OnboardNormal3Activity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal3_fragments_FirstOnboard3ItemFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal3_fragments_SecondOnboard3ItemFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal_OnboardNormalActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal_fragment_ChillSecondOnboardNormalFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal_fragment_FirstOnboardNormalFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_onboard_normal_fragment_SecondOnboardNormalFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_scan_photo_ScanPhotoActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_scan_photo_fragments_ScanPhotoFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_scan_photo_fragments_ScanPhotoResultFragment_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_splash_SplashActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_upload_image_UploadImageActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_ArtViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_ArtViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_BubbleViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_BubbleViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_CharacterViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_CharacterViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_ChatViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_ChatViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_CountryViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_CountryViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_CropImageViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_CropImageViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_GrammarViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_GrammarViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_MainViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_MainViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_OnboardViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_OnboardViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_PdfViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_PdfViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_ScanPhotoViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_ScanPhotoViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_SplashViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_SplashViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_SupportPurchasedViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_SupportPurchasedViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_TopicViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_TopicViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_TrackingViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_TrackingViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_UploadImageViewModel_HiltModules_BindsModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_viewmodel_UploadImageViewModel_HiltModules_KeyModule;,
        Lhilt_aggregated_deps/_com_android_ntduc_chatgpt_ui_component_widget_StartChatWidgetConfigureActivity_GeneratedInjector;,
        Lhilt_aggregated_deps/_dagger_hilt_android_flags_FragmentGetContextFix_FragmentGetContextFixEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_flags_HiltWrapper_FragmentGetContextFix_FragmentGetContextFixModule;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_lifecycle_DefaultViewModelFactories_ActivityEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_lifecycle_DefaultViewModelFactories_FragmentEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_lifecycle_HiltViewModelFactory_ViewModelFactoriesEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_lifecycle_HiltWrapper_DefaultViewModelFactories_ActivityModule;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_lifecycle_HiltWrapper_HiltViewModelFactory_ActivityCreatorEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_lifecycle_HiltWrapper_HiltViewModelFactory_ViewModelModule;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_managers_ActivityComponentManager_ActivityComponentBuilderEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_managers_FragmentComponentManager_FragmentComponentBuilderEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_managers_HiltWrapper_ActivityRetainedComponentManager_ActivityRetainedComponentBuilderEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_managers_HiltWrapper_ActivityRetainedComponentManager_ActivityRetainedLifecycleEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_managers_HiltWrapper_ActivityRetainedComponentManager_LifecycleModule;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_managers_ServiceComponentManager_ServiceComponentBuilderEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_managers_ViewComponentManager_ViewComponentBuilderEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_managers_ViewComponentManager_ViewWithFragmentComponentBuilderEntryPoint;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_modules_ApplicationContextModule;,
        Lhilt_aggregated_deps/_dagger_hilt_android_internal_modules_HiltWrapper_ActivityModule;
    }
    defineComponentDeps = {
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_components_ActivityComponent;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_components_ActivityRetainedComponent;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_components_FragmentComponent;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_components_ServiceComponent;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_components_ViewComponent;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_components_ViewModelComponent;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_components_ViewWithFragmentComponent;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_internal_builders_ActivityComponentBuilder;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_internal_builders_ActivityRetainedComponentBuilder;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_internal_builders_FragmentComponentBuilder;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_internal_builders_ServiceComponentBuilder;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_internal_builders_ViewComponentBuilder;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_internal_builders_ViewModelComponentBuilder;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_android_internal_builders_ViewWithFragmentComponentBuilder;,
        Ldagger/hilt/processor/internal/definecomponent/codegen/_dagger_hilt_components_SingletonComponent;
    }
    rootDeps = {
        Ldagger/hilt/internal/aggregatedroot/codegen/_com_android_ntduc_chatgpt_App;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
